name: Lint YAML files

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  yamllint:
    name: Run yamllint
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Report env
        run: |
          mkdir -p yaml-reports
          touch yaml-reports/yamllint-report.log

      - name: Run yamllint and save to log
        run: |
          FILES=$(git ls-files '*.yml' '*.yaml')
          if [ -n "$FILES" ]; then
            yamllint $FILES >> yaml-reports/yamllint-report.log
          else
            echo "No YAML files found." | tee yamllint-report.log
          fi


