name: Lint YAML files

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  yamllint:
    name: Run yamllint
    runs-on: self-hosted
    env:
      ACCEPT_RISK: ${{ vars.ACCEPT_RISK_YAML || 'true' }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x ./scripts/linting.sh
          ./scripts/linting.sh